# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

write_trace_cpp <- function(filename, jobs) {
    invisible(.Call('RSlurmSimTools_write_trace_cpp', PACKAGE = 'RSlurmSimTools', filename, jobs))
}

