---
title: "Analysing SLRUM Real and Simulated Backfill"
output:
  html_document: default
  html_notebook: default
---


```{r setup, echo=TRUE, results="hide",warning=TRUE,message=FALSE}
library(ggplot2)
library(gridExtra)
library(scales)
library(lubridate)
library(stringr)

library(rPython)
library(Rcpp)
library(plyr)

#some global locations
top_dir <- "/home/mikola/slurm_simulator3/slurm_sim_tools/validation"

real_top_dir <- "/home/mikola/slurm_simulator3/slurm_real/5"
sim_top_dir <- "/home/mikola/slurm_simulator3/sim/micro3/results"

setwd(top_dir)
source("../Rutil/trace_job_util.R")
```

# Reads Data

```{r}
sacct_r <- read_sacct_out(file.path(real_top_dir,"slurm_acct.out"))
sacct_r$ref_job_id <- as.integer(sub("\\.sh","",sacct_r$JobName))
sacct_r$Slurm <- "Real"
sacct_r$NTasks <- NULL
sacct_r$ReqGRES <- NULL

sacct_s <- read_sacct_out(file.path(sim_top_dir,"jobcomp.log"))
sacct_s$ref_job_id <- as.integer(sacct_s$JobName)
sacct_s$Slurm <- "Simulated"

sacctM <- merge(sacct_r,sacct_s,by="local_job_id",all=TRUE,suffixes = c("_r","_s"))
sacctRB <- rbind(sacct_r,sacct_s)
```

```{r}
bf_s <- read.csv(file.path(sim_top_dir,"simstat_backfill.csv"))
colnames(bf_s)[colnames(bf_s) == 'output_time'] <- 't'
for(col in c("t","last_cycle_when"))bf_s[,col] <- as.POSIXct(bf_s[,col],format = "%Y-%m-%d %H:%M:%S")
#drop duplicates
bf_s<-bf_s[bf_s$last_cycle_when>as.POSIXct("2001-01-01"),]
bf_s<-bf_s[!duplicated(bf_s$last_cycle_when),]
bf_s$t <- bf_s$last_cycle_when
bf_s$run_sim_time <- bf_s$last_cycle/1000000.0

sdiag_r <- read.csv(file.path(real_top_dir,"sdiag.csv"))
for(col in c("sdiag_output_time","data_since","backfil_stats__last_cycle_when"))sdiag_r[,col] <- as.POSIXct(sdiag_r[,col],format = "%Y-%m-%d %H:%M:%S")

bf_r <- sdiag_r[sdiag_r$backfil_stats__last_cycle_when>as.POSIXct("2001-01-01"),c(
    "backfil_stats__last_cycle_when",
    "backfil_stats__last_cycle",
    "backfil_stats__last_depth_cycle",
    "backfil_stats__last_depth_cycle_try_sched",
    "backfil_stats__last_queue_length"
)]
colnames(bf_r) <- sub("backfil_stats__","",colnames(bf_r))
#drop duplicates
bf_r<-bf_r[!duplicated(bf_r$last_cycle_when),]
bf_r$t <- bf_r$last_cycle_when
bf_r$run_real_time <- bf_r$last_cycle/1000000.0
```

# Plots

```{r, fig.width=20, fig.height=8}
grid.arrange(
    ggplot(bf_r,aes(x=t,y=run_real_time))+ggtitle("Real")+
        geom_point(size=1,colour="blue",alpha=0.25),
    ggplot(bf_r,aes(x=last_depth_cycle_try_sched,y=run_real_time))+ggtitle("Real")+
        geom_point(size=1,colour="blue",alpha=0.25)+stat_function(fun = function(x){0.004856*(x^0.575349)},n=100),
    ggplot(bf_r,aes(x=log10(last_depth_cycle_try_sched),y=log10(run_real_time)))+ggtitle("Real")+
        geom_point(size=1,colour="blue",alpha=0.25)+geom_smooth(method = "lm", colour = "black",formula = y~x),
    
    ggplot(bf_s,aes(x=t,y=run_sim_time))+ggtitle("Simulated")+
        geom_point(size=1,colour="blue",alpha=0.25),
    ggplot(bf_s,aes(x=last_depth_cycle_try_sched,y=run_sim_time))+ggtitle("Simulated")+
        geom_point(size=1,colour="blue",alpha=0.25),
    ggplot(bf_s,aes(x=log10(last_depth_cycle_try_sched),y=log10(run_sim_time)))+ggtitle("Simulated")+
        geom_point(size=1,colour="blue",alpha=0.25)+geom_smooth(method = "lm", colour = "black",formula = y~x),
    
    ggplot(bf_s,aes(x=t,y=run_real_time))+ggtitle("Simulated Actual")+
        geom_point(size=1,colour="blue",alpha=0.25),
    ggplot(bf_s,aes(x=last_depth_cycle_try_sched,y=run_real_time))+ggtitle("Simulated Actual")+
        geom_point(size=1,colour="blue",alpha=0.25),
    ggplot(bf_s,aes(x=log10(last_depth_cycle_try_sched),y=log10(run_real_time)))+ggtitle("Simulated Actual")+
        geom_point(size=1,colour="blue",alpha=0.25)+geom_smooth(method = "lm", colour = "black",formula = y~x),
    ncol=3)
```


# Fit
```{r, fig.width=20, fig.height=8}

fit_r <- lm(log10(run_real_time)~log10(last_depth_cycle_try_sched),bf_r[bf_r$last_depth_cycle_try_sched!=0,])
summary(fit_r)
Yr<-coef(fit_r)[[1]]
Kr<-coef(fit_r)[[2]]
b_r <- Kr
a_r <- 10**(Yr/Kr)


nls(run_real_time~a*last_depth_cycle_try_sched^b,start = list(a = 1, b = 3),data=bf_r[bf_r$last_depth_cycle_try_sched!=0,])
nls(run_real_time~a*last_depth_cycle_try_sched^b,start = list(a = 1, b = 3),data=bf_s[bf_s$last_depth_cycle_try_sched!=0,],
    control = nls.control(maxiter = 500))


nls(run_real_time~a*last_depth_cycle_try_sched,start = list(a = 1),data=bf_r[bf_r$last_depth_cycle_try_sched!=0,])
nls(run_real_time~a*last_depth_cycle_try_sched,start = list(a = 1),data=bf_s[bf_s$last_depth_cycle_try_sched!=0,],
    control = nls.control(maxiter = 500))

fit_s <- lm(log10(run_real_time)~log10(last_depth_cycle_try_sched),bf_s[bf_s$last_depth_cycle_try_sched!=0,])


```
