// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// write_trace_cpp
void write_trace_cpp(const char * filename, DataFrame jobs);
RcppExport SEXP RSlurmSimTools_write_trace_cpp(SEXP filenameSEXP, SEXP jobsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char * >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type jobs(jobsSEXP);
    write_trace_cpp(filename, jobs);
    return R_NilValue;
END_RCPP
}
